# Generated by Django 3.2.8 on 2022-01-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='FormalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('contract', models.TextField()),
                ('pdf', models.FileField(null=True, upload_to='')),
                ('state', models.CharField(choices=[('SI', 'Signed'), ('NS', 'Not Signed')], default='SI', max_length=2)),
                ('encounterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounterId', to='offer.encounter')),
            ],
        ),
    ]
