# Generated by Django 3.2.8 on 2021-11-29 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_formaloffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
