# Generated by Django 3.2.8 on 2021-12-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_encounter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaloffer',
            name='signedPdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
