# Generated by Django 3.2.8 on 2021-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_formaloffer_signedpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formaloffer',
            old_name='signedPdf',
            new_name='pdf',
        ),
        migrations.AddField(
            model_name='formaloffer',
            name='state',
            field=models.CharField(choices=[('SI', 'Signed'), ('NS', 'Not Signed')], default='SI', max_length=2),
        ),
    ]
