version: '3.7'

services:
  web:
    container_name: commed-backend
    build: .
    env_file:
      - .env
    command: sh ./docker-web-script.sh
    volumes:
      - .:/app
    ports:
      - ${OPEN_PORT}:${DJANGO_PORT}
    depends_on:
      - database
    restart: always
    stdin_open: true
    tty: true
  database:
    image: postgres:14-alpine
    container_name: commed-database
    env_file:
      - .env
    volumes:
      # /host/path:/container/path
      - ../database/data:/var/lib/postgresql/data
volumes:
  database:
