version: '3.7'

services:
  web:
    container_name: commed-backend
    build: .
    env_file:
      - .env
    command: sh ./docker-web-script.sh
    volumes:
      - .:/app
    ports:
      - ${OPEN_PORT}:${DJANGO_PORT}
    depends_on:
      - database
      - redis-back
    restart: always
    stdin_open: true
    tty: true
  database:
    image: postgres:14-alpine
    container_name: commed-database
    ports:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      # /host/path:/container/path
      - ../database/data:/var/lib/postgresql/data
  redis-back:
    image: redis
    container_name: commed-redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_INTERNAL_PORT}

volumes:
  database:
