# Generated by Django 3.2.8 on 2021-11-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0003_alter_encounter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel_context', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='offer.encounter')),
            ],
        ),
    ]
