# Generated by Django 3.2.8 on 2021-10-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=128)),
                ('contactInfo', models.CharField(max_length=256)),
                ('description', models.TextField(help_text='Description about the entity. It can be provided HTML')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
