# Generated by Django 3.2.8 on 2022-01-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('contactInfo', models.CharField(max_length=256)),
                ('description', models.TextField(default='', help_text='Description about the entity. It can be provided HTML')),
                ('profileImage', models.ImageField(default='profile.png', upload_to='images/')),
                ('bannerImage', models.ImageField(default='banner.jpg', upload_to='images/')),
                ('location', models.CharField(default='No location', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
