# Generated by Django 3.2.8 on 2021-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_enterprise_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='bannerImage',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='profileImage',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
