# Generated by Django 3.2.8 on 2021-12-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_enterprise_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='NIF',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
