# Generated by Django 3.2.8 on 2021-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20211122_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='bannerImage',
            field=models.ImageField(default='/static/images/banner.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='profileImage',
            field=models.ImageField(default='/static/images/profile.png', upload_to='images/'),
        ),
    ]
