# Generated by Django 3.2.8 on 2021-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_auto_20211122_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='bannerImage',
            field=models.ImageField(default='images/banner.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='profileImage',
            field=models.ImageField(default='images/profile.png', upload_to='images/'),
        ),
    ]
