# Generated by Django 3.2.8 on 2021-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_enterprise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='location',
            field=models.CharField(default='No location', max_length=100),
        ),
    ]
